// Code generated by goctl. DO NOT EDIT.
package types

type ShowRequest struct {
}

type ShowResponse struct {
	Expedition ExpeditionResponse `json:"expedition"`
	Sector     SectorResponse     `json:"sector"`
}

type GetExpeditionRequest struct {
}

type UpdateExpeditionRequest struct {
	ID string `json:"id"`
}

type ExpeditionResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type GetSectorRequest struct {
}

type UpdateSectorRequest struct {
	Name string `json:"name"`
}

type SectorResponse struct {
	Name string `json:"name,options=Main|Secondary|Overload|Prisoner Efficiency"`
}
