// Code generated by goctl. DO NOT EDIT.
package types

type ExpeditionURLReference struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type RundownIndexItem struct {
	ID          int                      `json:"id"`
	Name        string                   `json:"name"`
	Expeditions []ExpeditionURLReference `json:"expeditions"`
}

type ListRundownRequest struct {
}

type ListRundownResponse struct {
	Rundowns []RundownIndexItem `json:"rundowns"`
}

type ShowRundownRequest struct {
	RundownID string `path:"id"`
}

type ShowRundownResponse struct {
	ID          string                   `json:"id"`
	Name        string                   `json:"name"`
	Expeditions []ShowExpeditionResponse `json:"expeditions"`
}

type ListRundownExpeditionsRequest struct {
	RundownID string `path:"rundown_id"`
}

type ListRundownExpeditionsResponse struct {
	Expeditions []ExpeditionURLReference `json:"expeditions"`
}

type ShowExpeditionRequest struct {
	RundownID    string `path:"rundown_id"`
	ExpeditionID string `path:"expedition_id"`
}

type ShowExpeditionResponse struct {
	ID                        string          `json:"id"`
	Name                      string          `json:"name"`
	Depth                     int             `json:"depth"`
	Intel                     string          `json:"intel"`
	Extended                  bool            `json:"extended"`
	InterruptedCommunications string          `json:"interrupted_communications"`
	Sectors                   []SectorDetails `json:"sectors"`
}

type SectorDetails struct {
	Name       string                  `json:"name"`
	Objectives []SectorObjectiveDetail `json:"objectives"`
}

type SectorObjectiveDetail struct {
	Kind     string           `json:"kind"`
	Metadata []SectorMetadata `json:"metadata"`
}

type SectorMetadata struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
